#define SYMBOL_TABLE 1
#define VOID 2
#define NIL 7
#define FALSE 3
#define TRUE  5

/* THIS IS THE START OF THE PROGRAN */
#include <stdio.h>
#include <stdlib.h>

/* change to 0 for no debug info to be printed: */
#define DO_SHOW 1

#define db {printf("LINE: %d\n",__LINE__);}
#include "arch/cisc.h"
#include "debug.h"
int main()
{
  START_MACHINE;

  JUMP(CONTINUE);

#include "arch/char.lib"
#include "arch/io.lib"
#include "arch/math.lib"
#include "arch/string.lib"
#include "arch/system.lib"
#include "arch/scheme.lib"
  CONTINUE:
  PUSH(IMM(0)); 
  PUSH(IMM(0));
  PUSH(IMM(0));
  PUSH(IMM(0));
  MOV(FP,SP);


PUSH(IMM(501+1)); 
CALL(MALLOC); 
MOV(R0,IMM(2)); 
DROP(1); 
 
MOV(IND(R0),IMM(937610));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(0));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(722689));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(6));
 INCR(R0);
MOV(IND(R0),IMM(102));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(99));
 INCR(R0);
MOV(IND(R0),IMM(116));
 INCR(R0);
MOV(IND(R0),IMM(45));
 INCR(R0);
MOV(IND(R0),IMM(49));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(8));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(6));
 INCR(R0);
MOV(IND(R0),IMM(102));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(99));
 INCR(R0);
MOV(IND(R0),IMM(116));
 INCR(R0);
MOV(IND(R0),IMM(45));
 INCR(R0);
MOV(IND(R0),IMM(50));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(18));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(6));
 INCR(R0);
MOV(IND(R0),IMM(102));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(99));
 INCR(R0);
MOV(IND(R0),IMM(116));
 INCR(R0);
MOV(IND(R0),IMM(45));
 INCR(R0);
MOV(IND(R0),IMM(51));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(30));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(10));
 INCR(R0);

 /*starting global env------------*/ 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 

/* STARTING TO ADD PRIMITIVES */ 
 INCR(R0); 
MOV(IND(43),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cdr));
INCR(R0); 
MOV(IND(44),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_car));
INCR(R0); 
MOV(IND(45),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cons));
INCR(R0); 
MOV(IND(46),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_zero));
INCR(R0); 
MOV(IND(47),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_null));
INCR(R0); 
MOV(IND(48),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_list));
INCR(R0); 
MOV(IND(49),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_pair));
INCR(R0); 
MOV(IND(50),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_plus));
INCR(R0); 
MOV(IND(51),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_minus));
INCR(R0); 
MOV(IND(52),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_mult));
INCR(R0); 
MOV(IND(53),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_div));
INCR(R0); 
MOV(IND(54),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector));
INCR(R0); 
MOV(IND(55),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_apply));
INCR(R0); 
MOV(IND(56),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_string));
INCR(R0); 
MOV(IND(57),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_eq));
INCR(R0); 
MOV(IND(58),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_int));
INCR(R0); 
MOV(IND(59),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_lt));
INCR(R0); 
MOV(IND(60),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_gt));
INCR(R0); 
MOV(IND(61),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_eq));
INCR(R0); 
MOV(IND(62),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_to_symbol));
INCR(R0); 
MOV(IND(63),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_symbol_to_string));
INCR(R0); 
MOV(IND(64),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_vector));
INCR(R0); 
MOV(IND(65),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_bool));
INCR(R0); 
MOV(IND(66),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_string));
INCR(R0); 
MOV(IND(67),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_symbol));
INCR(R0); 
MOV(IND(68),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_vector));
INCR(R0); 
MOV(IND(69),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_proc));
INCR(R0); 
MOV(IND(70),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vec_len));
INCR(R0); 
MOV(IND(71),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_len));
INCR(R0); 
MOV(IND(72),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_denominator));
INCR(R0); 
MOV(IND(73),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_ref));
INCR(R0); 
MOV(IND(74),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_ref));
INCR(R0); 
MOV(IND(75),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_char_to_integer));
INCR(R0); 
MOV(IND(76),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_integer_to_char));
INCR(R0); 
MOV(IND(77),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_remainder));
INCR(R0); 
MOV(IND(78),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_number));
INCR(R0); 
MOV(IND(79),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_numerator));
INCR(R0); 
MOV(IND(80),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_rational));
INCR(R0); 
MOV(IND(81),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_car));
INCR(R0); 
MOV(IND(82),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_cdr));
INCR(R0); 
MOV(IND(83),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_set));
INCR(R0); 
MOV(IND(84),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_set));
INCR(R0); 
MOV(IND(85),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_char));
INCR(R0); 

 //STRING LIST
MOV(IND(1),R0); 
MOV(INDD(R0,0), IMM(8)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(18)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(30)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R0,0), IMM(T_UNDEFINED)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 


 /*new expr */ 
 
/* IN DEFINE +*/
MOV(R0,IND(50)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(86), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE -*/
MOV(R0,IND(51)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(87), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE **/
MOV(R0,IND(52)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(88), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE /*/
MOV(R0,IND(53)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(89), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE <*/
MOV(R0,IND(59)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(90), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE >*/
MOV(R0,IND(60)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(91), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE =*/
MOV(R0,IND(61)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(92), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-string*/
MOV(R0,IND(56)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(93), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-vector*/
MOV(R0,IND(64)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(94), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-ref*/
MOV(R0,IND(73)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(95), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-ref*/
MOV(R0,IND(74)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(96), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-length*/
MOV(R0,IND(71)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(97), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-length*/
MOV(R0,IND(70)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(98), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE eq?*/
MOV(R0,IND(57)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(99), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE zero?*/
MOV(R0,IND(46)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(100), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE null?*/
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(101), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE pair?*/
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(102), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list?*/
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(103), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol?*/
MOV(R0,IND(67)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(104), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string?*/
MOV(R0,IND(66)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(105), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector?*/
MOV(R0,IND(68)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(106), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE rational?*/
MOV(R0,IND(80)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(107), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE procedure?*/
MOV(R0,IND(69)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(108), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE number?*/
MOV(R0,IND(78)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(109), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer?*/
MOV(R0,IND(58)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(110), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char?*/
MOV(R0,IND(85)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(111), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE boolean?*/
MOV(R0,IND(65)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(112), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-cdr!*/
MOV(R0,IND(82)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(113), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-car!*/
MOV(R0,IND(81)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(114), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-set!*/
MOV(R0,IND(84)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(115), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-set!*/
MOV(R0,IND(83)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(116), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char->integer*/
MOV(R0,IND(75)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(117), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer->char*/
MOV(R0,IND(76)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(118), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol->string*/
MOV(R0,IND(63)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(119), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string->symbol*/
MOV(R0,IND(62)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(120), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop145: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit45); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop145);
lambda_loop1_exit45: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop245: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit45); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop245); 
lambda_loop2_exit45: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda45));
JUMP(exit45); 
lambda45:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop9:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt9); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop9);
finish_lambda_opt9: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case9); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case9); 
stack_fix9: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end9); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix9); 
empty_opt_case9:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt9:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt9); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt9);
end_of_nil_case_opt9: 
MOV(STACK(R6),R2); 
stack_fix_end9: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
MOV(R0,FPARG(2));
POP(FP);
RETURN;
exit45: //OUT OF LAMBDA 

 MOV(IND(121), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldl*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop146: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit46); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop146);
lambda_loop1_exit46: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop246: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit46); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop246); 
lambda_loop2_exit46: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda46));
JUMP(exit46); 
lambda46:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(101)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else24);
MOV(R0,FPARG(3));

JUMP(if_exit24);
else24:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(43)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(122)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy40:
CMP(R3,R5); 
JUMP_EQ(jmpa40); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy40); 
jmpa40: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit24:
POP(FP);
RETURN;
exit46: //OUT OF LAMBDA 

 MOV(IND(122), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldr*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop147: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit47); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop147);
lambda_loop1_exit47: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop247: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit47); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop247); 
lambda_loop2_exit47: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda47));
JUMP(exit47); 
lambda47:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(101)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else25);
MOV(R0,FPARG(3));

JUMP(if_exit25);
else25:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(43)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(123)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy41:
CMP(R3,R5); 
JUMP_EQ(jmpa41); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy41); 
jmpa41: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit25:
POP(FP);
RETURN;
exit47: //OUT OF LAMBDA 

 MOV(IND(123), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE reverse*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop148: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit48); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop148);
lambda_loop1_exit48: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop248: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit48); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop248); 
lambda_loop2_exit48: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda48));
JUMP(exit48); 
lambda48:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(101)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else27);
MOV(R0,FPARG(3));

JUMP(if_exit27);
else27:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(103)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(127)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else26);
MOV(R0,FPARG(2));

JUMP(if_exit26);
else26:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(43)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(124)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy42:
CMP(R3,R5); 
JUMP_EQ(jmpa42); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy42); 
jmpa42: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit26:
if_exit27:
POP(FP);
RETURN;
exit48: //OUT OF LAMBDA 

 MOV(IND(124), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE bin_append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop149: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit49); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop149);
lambda_loop1_exit49: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop249: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit49); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop249); 
lambda_loop2_exit49: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda49));
JUMP(exit49); 
lambda49:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(101)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else29);
MOV(R0,FPARG(3));

JUMP(if_exit29);
else29:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(103)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(127)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else28);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy44:
CMP(R3,R5); 
JUMP_EQ(jmpa44); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy44); 
jmpa44: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit28);
else28:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(43)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(125)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy43:
CMP(R3,R5); 
JUMP_EQ(jmpa43); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy43); 
jmpa43: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit28:
if_exit29:
POP(FP);
RETURN;
exit49: //OUT OF LAMBDA 

 MOV(IND(125), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop150: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit50); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop150);
lambda_loop1_exit50: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop250: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit50); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop250); 
lambda_loop2_exit50: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda50));
JUMP(exit50); 
lambda50:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop10:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt10); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop10);
finish_lambda_opt10: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case10); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case10); 
stack_fix10: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end10); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix10); 
empty_opt_case10:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt10:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt10); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt10);
end_of_nil_case_opt10: 
MOV(STACK(R6),R2); 
stack_fix_end10: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop151: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit51); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop151);
lambda_loop1_exit51: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop251: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit51); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop251); 
lambda_loop2_exit51: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda51));
JUMP(exit51); 
lambda51:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(7)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(124)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(125)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy45:
CMP(R3,R5); 
JUMP_EQ(jmpa45); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy45); 
jmpa45: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit51: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop152: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit52); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop152);
lambda_loop1_exit52: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop252: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit52); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop252); 
lambda_loop2_exit52: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda52));
JUMP(exit52); 
lambda52:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
MOV(R0,IMM(7)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(123)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy46:
CMP(R3,R5); 
JUMP_EQ(jmpa46); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy46); 
jmpa46: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit52: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy47:
CMP(R3,R5); 
JUMP_EQ(jmpa47); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy47); 
jmpa47: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit50: //OUT OF LAMBDA 

 MOV(IND(126), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE not*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop153: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit53); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop153);
lambda_loop1_exit53: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop253: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit53); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop253); 
lambda_loop2_exit53: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda53));
JUMP(exit53); 
lambda53:
PUSH(FP);
MOV(FP,SP);
MOV(R0,FPARG(2));

CMP(R0,FALSE);

JUMP_EQ(else30);
MOV(R0,IMM(3)); 

JUMP(if_exit30);
else30:
MOV(R0,IMM(5)); 
if_exit30:
POP(FP);
RETURN;
exit53: //OUT OF LAMBDA 

 MOV(IND(127), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map_simple*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop154: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit54); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop154);
lambda_loop1_exit54: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop254: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit54); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop254); 
lambda_loop2_exit54: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda54));
JUMP(exit54); 
lambda54:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(7)); 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(124)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop155: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit55); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop155);
lambda_loop1_exit55: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop255: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit55); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop255); 
lambda_loop2_exit55: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda55));
JUMP(exit55); 
lambda55:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,IMM(7)); 
PUSH(R0); 
// IN LAMBDA AAAAA 
MOV(R1,1+2); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop156: 
CMP(R4,2); 
JUMP_GE(lambda_loop1_exit56); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop156);
lambda_loop1_exit56: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop256: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit56); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop256); 
lambda_loop2_exit56: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda56));
JUMP(exit56); 
lambda56:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,1));
MOV(R0,INDD(R0,0));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy48:
CMP(R3,R5); 
JUMP_EQ(jmpa48); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy48); 
jmpa48: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit56: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(122)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy49:
CMP(R3,R5); 
JUMP_EQ(jmpa49); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy49); 
jmpa49: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit55: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy50:
CMP(R3,R5); 
JUMP_EQ(jmpa50); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy50); 
jmpa50: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit54: //OUT OF LAMBDA 

 MOV(IND(128), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop157: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit57); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop157);
lambda_loop1_exit57: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop257: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit57); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop257); 
lambda_loop2_exit57: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda57));
JUMP(exit57); 
lambda57:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop11:
 CMP(R1,1);
 JUMP_EQ(finish_lambda_opt11); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop11);
finish_lambda_opt11: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case11); 
MOV(FPARG(2+1),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+1);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case11); 
stack_fix11: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end11); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix11); 
empty_opt_case11:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt11:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt11); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt11);
end_of_nil_case_opt11: 
MOV(STACK(R6),R2); 
stack_fix_end11: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(101)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else31);
MOV(R0,IMM(7)); 

JUMP(if_exit31);
else31:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(43)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(128)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(128)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(55)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop158: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit58); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop158);
lambda_loop1_exit58: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop258: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit58); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop258); 
lambda_loop2_exit58: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda58));
JUMP(exit58); 
lambda58:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IND(129)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(55)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy51:
CMP(R3,R5); 
JUMP_EQ(jmpa51); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy51); 
jmpa51: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit58: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy52:
CMP(R3,R5); 
JUMP_EQ(jmpa52); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy52); 
jmpa52: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit31:
POP(FP);
RETURN;
exit57: //OUT OF LAMBDA 

 MOV(IND(129), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE with*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop159: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit59); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop159);
lambda_loop1_exit59: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop259: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit59); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop259); 
lambda_loop2_exit59: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda59));
JUMP(exit59); 
lambda59:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(55)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy53:
CMP(R3,R5); 
JUMP_EQ(jmpa53); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy53); 
jmpa53: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit59: //OUT OF LAMBDA 

 MOV(IND(130), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE fact-1*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop160: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit60); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop160);
lambda_loop1_exit60: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop260: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit60); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop260); 
lambda_loop2_exit60: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda60));
JUMP(exit60); 
lambda60:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(100)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else32);
//IN APPLIC 
MOV(R0,IMM(16)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(121)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy56:
CMP(R3,R5); 
JUMP_EQ(jmpa56); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy56); 
jmpa56: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit32);
else32:
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop161: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit61); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop161);
lambda_loop1_exit61: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop261: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit61); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop261); 
lambda_loop2_exit61: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda61));
JUMP(exit61); 
lambda61:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop12:
 CMP(R1,1);
 JUMP_EQ(finish_lambda_opt12); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop12);
finish_lambda_opt12: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case12); 
MOV(FPARG(2+1),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+1);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case12); 
stack_fix12: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end12); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix12); 
empty_opt_case12:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt12:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt12); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt12);
end_of_nil_case_opt12: 
MOV(STACK(R6),R2); 
stack_fix_end12: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IMM(16)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(88)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy54:
CMP(R3,R5); 
JUMP_EQ(jmpa54); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy54); 
jmpa54: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit61: //OUT OF LAMBDA 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(132)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(130)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy55:
CMP(R3,R5); 
JUMP_EQ(jmpa55); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy55); 
jmpa55: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit32:
POP(FP);
RETURN;
exit60: //OUT OF LAMBDA 

 MOV(IND(131), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE fact-2*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop162: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit62); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop162);
lambda_loop1_exit62: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop262: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit62); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop262); 
lambda_loop2_exit62: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda62));
JUMP(exit62); 
lambda62:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(100)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else33);
//IN APPLIC 
MOV(R0,IMM(26)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(121)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy59:
CMP(R3,R5); 
JUMP_EQ(jmpa59); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy59); 
jmpa59: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit33);
else33:
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop163: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit63); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop163);
lambda_loop1_exit63: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop263: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit63); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop263); 
lambda_loop2_exit63: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda63));
JUMP(exit63); 
lambda63:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop13:
 CMP(R1,1);
 JUMP_EQ(finish_lambda_opt13); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop13);
finish_lambda_opt13: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case13); 
MOV(FPARG(2+1),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+1);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case13); 
stack_fix13: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end13); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix13); 
empty_opt_case13:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt13:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt13); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt13);
end_of_nil_case_opt13: 
MOV(STACK(R6),R2); 
stack_fix_end13: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IMM(26)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(88)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy57:
CMP(R3,R5); 
JUMP_EQ(jmpa57); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy57); 
jmpa57: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit63: //OUT OF LAMBDA 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(133)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(130)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy58:
CMP(R3,R5); 
JUMP_EQ(jmpa58); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy58); 
jmpa58: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit33:
POP(FP);
RETURN;
exit62: //OUT OF LAMBDA 

 MOV(IND(132), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE fact-3*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop164: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit64); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop164);
lambda_loop1_exit64: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop264: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit64); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop264); 
lambda_loop2_exit64: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda64));
JUMP(exit64); 
lambda64:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(100)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else34);
//IN APPLIC 
MOV(R0,IMM(38)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(121)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy62:
CMP(R3,R5); 
JUMP_EQ(jmpa62); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy62); 
jmpa62: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit34);
else34:
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop165: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit65); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop165);
lambda_loop1_exit65: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop265: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit65); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop265); 
lambda_loop2_exit65: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda65));
JUMP(exit65); 
lambda65:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop14:
 CMP(R1,1);
 JUMP_EQ(finish_lambda_opt14); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop14);
finish_lambda_opt14: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case14); 
MOV(FPARG(2+1),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+1);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case14); 
stack_fix14: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end14); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix14); 
empty_opt_case14:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt14:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt14); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt14);
end_of_nil_case_opt14: 
MOV(STACK(R6),R2); 
stack_fix_end14: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IMM(38)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(88)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy60:
CMP(R3,R5); 
JUMP_EQ(jmpa60); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy60); 
jmpa60: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit65: //OUT OF LAMBDA 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(131)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(130)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy61:
CMP(R3,R5); 
JUMP_EQ(jmpa61); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy61); 
jmpa61: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit34:
POP(FP);
RETURN;
exit64: //OUT OF LAMBDA 

 MOV(IND(133), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(40)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(131)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 
/*epilogue */ 


STOP_MACHINE;
return 0;
UNDEFINED_VARIABLE_ERROR:
printf("undefined variable \n");
L_ERROR_NOT_CLOSURE:
  printf("aaa\n");
  exit(12);
}
