#define VOID 2
#define NIL 3
#define FALSE 4
#define TRUE  6

/* THIS IS THE START OF THE PROGRAN */
#include <stdio.h>
#include <stdlib.h>

/* change to 0 for no debug info to be printed: */
#define DO_SHOW 1

#define db {printf("LINE: %d\n",__LINE__);}
#include "arch/cisc.h"
#include "debug.h"
int main()
{
  START_MACHINE;

  JUMP(CONTINUE);

#include "arch/char.lib"
#include "arch/io.lib"
#include "arch/math.lib"
#include "arch/string.lib"
#include "arch/system.lib"
#include "arch/scheme.lib"
  CONTINUE:
  PUSH(IMM(0));
  PUSH(IMM(0));
  PUSH(IMM(0));
  PUSH(IMM(0));
  MOV(FP,SP);


PUSH(IMM(213+1)); 
CALL(MALLOC); 
MOV(R0,IMM(2)); 
DROP(1); 
 
MOV(IND(R0),IMM(937610));
 INCR(R0);
MOV(IND(R0),IMM(722689));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(0));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(4));
 INCR(R0);

 /*starting global env------------*/ 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 

/* STARTING TO ADD PRIMITIVES */ 
MOV(IND(11),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_car));
INCR(R0); 
MOV(IND(12),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cdr));
INCR(R0); 
MOV(IND(13),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cons));
INCR(R0); 
MOV(IND(14),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_plus));
INCR(R0); 
MOV(IND(15),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_minus));
INCR(R0); 
MOV(IND(16),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_zero));
INCR(R0); 
MOV(IND(17),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_null));
INCR(R0); 
MOV(IND(18),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_mul));
INCR(R0); 
MOV(IND(19),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_list));
INCR(R0); 
MOV(IND(20),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_pair));
INCR(R0); 
MOV(IND(21),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_plus));
INCR(R0); 
MOV(IND(22),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_minus));
INCR(R0); 
MOV(IND(23),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_mult));
INCR(R0); 
MOV(IND(24),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_div));
INCR(R0); 
MOV(IND(25),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector));
INCR(R0); 
MOV(IND(26),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_apply));
INCR(R0); 
MOV(IND(27),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_string));
INCR(R0); 
MOV(IND(28),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_eq));
INCR(R0); 
MOV(IND(29),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_lt));
INCR(R0); 
MOV(IND(30),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_gt));
INCR(R0); 
MOV(IND(31),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_eq));
INCR(R0); 



 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(21)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(32), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(22)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(33), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(23)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(34), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(24)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(35), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(29)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(36), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(30)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(37), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(31)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(38), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(27)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(39), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(28)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(40), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(16)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(41), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(17)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(42), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(20)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(43), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
MOV(R0,IND(19)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(44), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 0; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda27));
JUMP(exit27); 
lambda27:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop6:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt6); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop6);
finish_lambda_opt6: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case6); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case6); 
stack_fix6: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end6); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix6); 
empty_opt_case6:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt6:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt6); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt6);
end_of_nil_case_opt6: 
MOV(STACK(R6),R2); 
stack_fix_end6: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
MOV(R0,FPARG(2));
POP(FP);
RETURN;
exit27: //OUT OF LAMBDA 

 MOV(IND(45), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 0; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda28));
JUMP(exit28); 
lambda28:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(42)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else21);
MOV(R0,FPARG(3));

JUMP(if_exit21);
else21:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(12)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(11)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(46)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy24:
CMP(R3,R5); 
JUMP_EQ(jmpa24); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy24); 
jmpa24: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit21:
POP(FP);
RETURN;
exit28: //OUT OF LAMBDA 

 MOV(IND(46), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 0; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda29));
JUMP(exit29); 
lambda29:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(42)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else22);
MOV(R0,FPARG(3));

JUMP(if_exit22);
else22:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(12)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(11)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy25:
CMP(R3,R5); 
JUMP_EQ(jmpa25); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy25); 
jmpa25: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit22:
POP(FP);
RETURN;
exit29: //OUT OF LAMBDA 

 MOV(IND(47), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 0; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda30));
JUMP(exit30); 
lambda30:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(42)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else24);
MOV(R0,FPARG(3));

JUMP(if_exit24);
else24:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(51)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else23);
MOV(R0,FPARG(2));

JUMP(if_exit23);
else23:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(11)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(13)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(12)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy26:
CMP(R3,R5); 
JUMP_EQ(jmpa26); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy26); 
jmpa26: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit23:
if_exit24:
POP(FP);
RETURN;
exit30: //OUT OF LAMBDA 

 MOV(IND(48), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 0; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda31));
JUMP(exit31); 
lambda31:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(42)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else26);
MOV(R0,FPARG(3));

JUMP(if_exit26);
else26:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(51)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else25);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(13)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy28:
CMP(R3,R5); 
JUMP_EQ(jmpa28); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy28); 
jmpa28: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit25);
else25:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(11)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(13)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(12)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy27:
CMP(R3,R5); 
JUMP_EQ(jmpa27); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy27); 
jmpa27: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit25:
if_exit26:
POP(FP);
RETURN;
exit31: //OUT OF LAMBDA 

 MOV(IND(49), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 0; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda32));
JUMP(exit32); 
lambda32:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop7:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt7); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop7);
finish_lambda_opt7: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case7); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case7); 
stack_fix7: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end7); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix7); 
empty_opt_case7:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt7:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt7); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt7);
end_of_nil_case_opt7: 
MOV(STACK(R6),R2); 
stack_fix_end7: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 1; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda33));
JUMP(exit33); 
lambda33:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(3)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy29:
CMP(R3,R5); 
JUMP_EQ(jmpa29); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy29); 
jmpa29: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit33: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 1; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda34));
JUMP(exit34); 
lambda34:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
MOV(R0,IMM(3)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy30:
CMP(R3,R5); 
JUMP_EQ(jmpa30); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy30); 
jmpa30: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit34: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy31:
CMP(R3,R5); 
JUMP_EQ(jmpa31); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy31); 
jmpa31: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit32: //OUT OF LAMBDA 

 MOV(IND(50), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
/* IN DEFINE*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
for(int i=0,j=1; i < 0; ++i, ++j){
     MOV(R3, INDD(R2,i));
     MOV(INDD(R1,j),R3);
   }
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
for(int i=0; i<FPARG(1); ++i){
     MOV(R3,FPARG(2+i));
     MOV(INDD(R0,i),R3);
    }
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda35));
JUMP(exit35); 
lambda35:
PUSH(FP);
MOV(FP,SP);
MOV(R0,FPARG(2));

CMP(R0,FALSE);

JUMP_EQ(else27);
MOV(R0,IMM(4)); 

JUMP(if_exit27);
else27:
MOV(R0,IMM(6)); 
if_exit27:
POP(FP);
RETURN;
exit35: //OUT OF LAMBDA 

 MOV(IND(51), R0);
MOV(R0,VOID); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(8)); 
PUSH(R0); 
MOV(R0,IMM(8)); 
PUSH(R0); 
MOV(R0,IMM(8)); 
PUSH(R0); 
MOV(R0,IMM(8)); 
PUSH(R0); 
PUSH(IMM(4)); 
MOV(R0,IND(38)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
/*epilogue */ 


PUSH(R0);
CALL(WRITE_SOB);
printf("\n");
DROP(1);
STOP_MACHINE;
return 0;
UNDEFINED_VARIABLE_ERROR:
printf("undefined variable \n");
L_ERROR_NOT_CLOSURE:
  printf("aaa\n");
  exit(12);
}
