#define SYMBOL_TABLE 1
#define VOID 2
#define NIL 18
#define FALSE 95
#define TRUE  93

/* THIS IS THE START OF THE PROGRAN */
#include <stdio.h>
#include <stdlib.h>

/* change to 0 for no debug info to be printed: */
#define DO_SHOW 1

#define db {printf("LINE: %d\n",__LINE__);}
#include "arch/cisc.h"
#include "debug.h"
int main()
{
  START_MACHINE;

  JUMP(CONTINUE);

#include "arch/char.lib"
#include "arch/io.lib"
#include "arch/math.lib"
#include "arch/string.lib"
#include "arch/system.lib"
#include "arch/scheme.lib"
  CONTINUE:
  PUSH(IMM(0)); 
  PUSH(IMM(0));
  PUSH(IMM(0));
  PUSH(IMM(0));
  MOV(FP,SP);


PUSH(IMM(638+1)); 
CALL(MALLOC); 
MOV(R0,IMM(2)); 
DROP(1); 
 
MOV(IND(R0),IMM(937610));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(120));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(121));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(8));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(122));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(13));
 INCR(R0);
MOV(IND(R0),IMM(722689));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(16));
 INCR(R0);
MOV(IND(R0),IMM(18));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(11));
 INCR(R0);
MOV(IND(R0),IMM(19));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(6));
 INCR(R0);
MOV(IND(R0),IMM(22));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(2));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(32));
 INCR(R0);
MOV(IND(R0),IMM(18));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(30));
 INCR(R0);
MOV(IND(R0),IMM(34));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(28));
 INCR(R0);
MOV(IND(R0),IMM(37));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(4));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(5));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(45));
 INCR(R0);
MOV(IND(R0),IMM(18));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(43));
 INCR(R0);
MOV(IND(R0),IMM(47));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(38));
 INCR(R0);
MOV(IND(R0),IMM(116));
 INCR(R0);
MOV(IND(R0),IMM(101));
 INCR(R0);
MOV(IND(R0),IMM(115));
 INCR(R0);
MOV(IND(R0),IMM(116));
 INCR(R0);
MOV(IND(R0),IMM(48));
 INCR(R0);
MOV(IND(R0),IMM(50));
 INCR(R0);
MOV(IND(R0),IMM(46));
 INCR(R0);
MOV(IND(R0),IMM(115));
 INCR(R0);
MOV(IND(R0),IMM(99));
 INCR(R0);
MOV(IND(R0),IMM(109));
 INCR(R0);
MOV(IND(R0),IMM(32));
 INCR(R0);
MOV(IND(R0),IMM(40));
 INCR(R0);
MOV(IND(R0),IMM(114));
 INCR(R0);
MOV(IND(R0),IMM(101));
 INCR(R0);
MOV(IND(R0),IMM(118));
 INCR(R0);
MOV(IND(R0),IMM(105));
 INCR(R0);
MOV(IND(R0),IMM(115));
 INCR(R0);
MOV(IND(R0),IMM(101));
 INCR(R0);
MOV(IND(R0),IMM(100));
 INCR(R0);
MOV(IND(R0),IMM(41));
 INCR(R0);
MOV(IND(R0),IMM(44));
 INCR(R0);
MOV(IND(R0),IMM(32));
 INCR(R0);
MOV(IND(R0),IMM(115));
 INCR(R0);
MOV(IND(R0),IMM(104));
 INCR(R0);
MOV(IND(R0),IMM(111));
 INCR(R0);
MOV(IND(R0),IMM(117));
 INCR(R0);
MOV(IND(R0),IMM(108));
 INCR(R0);
MOV(IND(R0),IMM(100));
 INCR(R0);
MOV(IND(R0),IMM(32));
 INCR(R0);
MOV(IND(R0),IMM(114));
 INCR(R0);
MOV(IND(R0),IMM(101));
 INCR(R0);
MOV(IND(R0),IMM(116));
 INCR(R0);
MOV(IND(R0),IMM(117));
 INCR(R0);
MOV(IND(R0),IMM(114));
 INCR(R0);
MOV(IND(R0),IMM(110));
 INCR(R0);
MOV(IND(R0),IMM(32));
 INCR(R0);
MOV(IND(R0),IMM(35));
 INCR(R0);
MOV(IND(R0),IMM(116));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(0));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(98));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(102));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(99));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(107));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(110));
 INCR(R0);
MOV(IND(R0),IMM(18));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(100));
 INCR(R0);
MOV(IND(R0),IMM(112));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(105));
 INCR(R0);
MOV(IND(R0),IMM(115));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(6));
 INCR(R0);
MOV(IND(R0),IMM(108));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(109));
 INCR(R0);
MOV(IND(R0),IMM(98));
 INCR(R0);
MOV(IND(R0),IMM(100));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(121));
 INCR(R0);
MOV(IND(R0),IMM(335728));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(28));
 INCR(R0);
MOV(IND(R0),IMM(30));
 INCR(R0);
MOV(IND(R0),IMM(32));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(1234));
 INCR(R0);
MOV(IND(R0),IMM(335728));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(105));
 INCR(R0);
MOV(IND(R0),IMM(93));
 INCR(R0);
MOV(IND(R0),IMM(18));
 INCR(R0);
MOV(IND(R0),IMM(885397));
 INCR(R0);
MOV(IND(R0),IMM(105));
 INCR(R0);
MOV(IND(R0),IMM(100));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(98));
 INCR(R0);
MOV(IND(R0),IMM(99));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(10000));
 INCR(R0);
MOV(IND(R0),IMM(335728));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(105));
 INCR(R0);
MOV(IND(R0),IMM(100));
 INCR(R0);
MOV(IND(R0),IMM(110));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(65));
 INCR(R0);
MOV(IND(R0),IMM(181048));
 INCR(R0);
MOV(IND(R0),IMM(65));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(0));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(98));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(2));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(98));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(168));
 INCR(R0);
MOV(IND(R0),IMM(181048));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(7));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(234));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(6));
 INCR(R0);

 /*starting global env------------*/ 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 

/* STARTING TO ADD PRIMITIVES */ 
 INCR(R0); 
MOV(IND(183),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cdr));
INCR(R0); 
MOV(IND(184),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_car));
INCR(R0); 
MOV(IND(185),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cons));
INCR(R0); 
MOV(IND(186),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_zero));
INCR(R0); 
MOV(IND(187),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_null));
INCR(R0); 
MOV(IND(188),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_list));
INCR(R0); 
MOV(IND(189),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_pair));
INCR(R0); 
MOV(IND(190),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_plus));
INCR(R0); 
MOV(IND(191),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_minus));
INCR(R0); 
MOV(IND(192),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_mult));
INCR(R0); 
MOV(IND(193),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_div));
INCR(R0); 
MOV(IND(194),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector));
INCR(R0); 
MOV(IND(195),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_apply));
INCR(R0); 
MOV(IND(196),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_string));
INCR(R0); 
MOV(IND(197),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_eq));
INCR(R0); 
MOV(IND(198),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_int));
INCR(R0); 
MOV(IND(199),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_lt));
INCR(R0); 
MOV(IND(200),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_gt));
INCR(R0); 
MOV(IND(201),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_eq));
INCR(R0); 
MOV(IND(202),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_to_symbol));
INCR(R0); 
MOV(IND(203),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_symbol_to_string));
INCR(R0); 
MOV(IND(204),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_vector));
INCR(R0); 
MOV(IND(205),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_bool));
INCR(R0); 
MOV(IND(206),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_string));
INCR(R0); 
MOV(IND(207),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_symbol));
INCR(R0); 
MOV(IND(208),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_vector));
INCR(R0); 
MOV(IND(209),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_proc));
INCR(R0); 
MOV(IND(210),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vec_len));
INCR(R0); 
MOV(IND(211),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_len));
INCR(R0); 
MOV(IND(212),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_denominator));
INCR(R0); 
MOV(IND(213),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_ref));
INCR(R0); 
MOV(IND(214),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_ref));
INCR(R0); 
MOV(IND(215),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_char_to_integer));
INCR(R0); 
MOV(IND(216),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_integer_to_char));
INCR(R0); 
MOV(IND(217),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_remainder));
INCR(R0); 
MOV(IND(218),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_number));
INCR(R0); 
MOV(IND(219),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_numerator));
INCR(R0); 
MOV(IND(220),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_rational));
INCR(R0); 
MOV(IND(221),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_car));
INCR(R0); 
MOV(IND(222),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_cdr));
INCR(R0); 
MOV(IND(223),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_set));
INCR(R0); 
MOV(IND(224),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_set));
INCR(R0); 
MOV(IND(225),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_char));
INCR(R0); 

 //STRING LIST
/* BEHOLD THE CREATION OF THE SYMBOL TABLE */ 
MOV(IND(1),R0); 
MOV(INDD(R0,0), IMM(3)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(8)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(13)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(97)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(102)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(107)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(121)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0), IMM(168)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R1,1),R0); 
MOV(INDD(R0,0),IMM(T_UNDEFINED));
MOV(INDD(R0,1),IMM(205774250));

 /*new expr */ 
 
/* IN DEFINE +*/
MOV(R0,IND(190)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(226), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE -*/
MOV(R0,IND(191)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(227), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE **/
MOV(R0,IND(192)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(228), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE /*/
MOV(R0,IND(193)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(229), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE <*/
MOV(R0,IND(199)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(230), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE >*/
MOV(R0,IND(200)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(231), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE =*/
MOV(R0,IND(201)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(232), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-string*/
MOV(R0,IND(196)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(233), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-vector*/
MOV(R0,IND(204)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(234), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-ref*/
MOV(R0,IND(213)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(235), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-ref*/
MOV(R0,IND(214)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(236), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-length*/
MOV(R0,IND(211)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(237), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-length*/
MOV(R0,IND(210)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(238), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE eq?*/
MOV(R0,IND(197)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(239), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE zero?*/
MOV(R0,IND(186)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(240), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE null?*/
MOV(R0,IND(187)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(241), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE pair?*/
MOV(R0,IND(189)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(242), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list?*/
MOV(R0,IND(188)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(243), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol?*/
MOV(R0,IND(207)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(244), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string?*/
MOV(R0,IND(206)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(245), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector?*/
MOV(R0,IND(208)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(246), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE rational?*/
MOV(R0,IND(220)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(247), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE procedure?*/
MOV(R0,IND(209)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(248), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE number?*/
MOV(R0,IND(218)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(249), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer?*/
MOV(R0,IND(198)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(250), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char?*/
MOV(R0,IND(225)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(251), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE boolean?*/
MOV(R0,IND(205)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(252), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-cdr!*/
MOV(R0,IND(222)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(253), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-car!*/
MOV(R0,IND(221)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(254), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-set!*/
MOV(R0,IND(224)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(255), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-set!*/
MOV(R0,IND(223)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(256), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char->integer*/
MOV(R0,IND(215)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(257), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer->char*/
MOV(R0,IND(216)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(258), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol->string*/
MOV(R0,IND(203)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(259), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string->symbol*/
MOV(R0,IND(202)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(260), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12797: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2797); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12797);
lambda_loop1_exit2797: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22797: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2797); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22797); 
lambda_loop2_exit2797: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2797));
JUMP(exit2797); 
lambda2797:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop231:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt231); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop231);
finish_lambda_opt231: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case231); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case231); 
stack_fix231: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end231); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix231); 
empty_opt_case231:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt231:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt231); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt231);
end_of_nil_case_opt231: 
MOV(STACK(R6),R2); 
stack_fix_end231: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
MOV(R0,FPARG(2));
POP(FP);
RETURN;
exit2797: //OUT OF LAMBDA 

 MOV(IND(261), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldl*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12798: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2798); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12798);
lambda_loop1_exit2798: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22798: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2798); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22798); 
lambda_loop2_exit2798: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2798));
JUMP(exit2798); 
lambda2798:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(241)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else1471);
MOV(R0,FPARG(3));

JUMP(if_exit1471);
else1471:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(183)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(262)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy1667:
CMP(R3,R5); 
JUMP_EQ(jmpa1667); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1667); 
jmpa1667: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit1471:
POP(FP);
RETURN;
exit2798: //OUT OF LAMBDA 

 MOV(IND(262), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldr*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12799: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2799); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12799);
lambda_loop1_exit2799: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22799: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2799); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22799); 
lambda_loop2_exit2799: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2799));
JUMP(exit2799); 
lambda2799:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(241)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else1472);
MOV(R0,FPARG(3));

JUMP(if_exit1472);
else1472:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(183)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(263)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy1668:
CMP(R3,R5); 
JUMP_EQ(jmpa1668); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1668); 
jmpa1668: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit1472:
POP(FP);
RETURN;
exit2799: //OUT OF LAMBDA 

 MOV(IND(263), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE reverse*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12800: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2800); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12800);
lambda_loop1_exit2800: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22800: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2800); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22800); 
lambda_loop2_exit2800: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2800));
JUMP(exit2800); 
lambda2800:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(241)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else1474);
MOV(R0,FPARG(3));

JUMP(if_exit1474);
else1474:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(243)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else1473);
MOV(R0,FPARG(2));

JUMP(if_exit1473);
else1473:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(183)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(264)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1669:
CMP(R3,R5); 
JUMP_EQ(jmpa1669); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1669); 
jmpa1669: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit1473:
if_exit1474:
POP(FP);
RETURN;
exit2800: //OUT OF LAMBDA 

 MOV(IND(264), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE bin_append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12801: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2801); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12801);
lambda_loop1_exit2801: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22801: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2801); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22801); 
lambda_loop2_exit2801: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2801));
JUMP(exit2801); 
lambda2801:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(241)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else1476);
MOV(R0,FPARG(3));

JUMP(if_exit1476);
else1476:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(243)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else1475);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1671:
CMP(R3,R5); 
JUMP_EQ(jmpa1671); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1671); 
jmpa1671: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit1475);
else1475:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(183)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(265)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1670:
CMP(R3,R5); 
JUMP_EQ(jmpa1670); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1670); 
jmpa1670: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit1475:
if_exit1476:
POP(FP);
RETURN;
exit2801: //OUT OF LAMBDA 

 MOV(IND(265), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12802: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2802); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12802);
lambda_loop1_exit2802: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22802: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2802); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22802); 
lambda_loop2_exit2802: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2802));
JUMP(exit2802); 
lambda2802:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop232:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt232); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop232);
finish_lambda_opt232: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case232); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case232); 
stack_fix232: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end232); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix232); 
empty_opt_case232:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt232:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt232); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt232);
end_of_nil_case_opt232: 
MOV(STACK(R6),R2); 
stack_fix_end232: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12803: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit2803); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12803);
lambda_loop1_exit2803: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22803: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2803); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22803); 
lambda_loop2_exit2803: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2803));
JUMP(exit2803); 
lambda2803:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(18)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(264)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(265)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1672:
CMP(R3,R5); 
JUMP_EQ(jmpa1672); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1672); 
jmpa1672: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2803: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12804: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit2804); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12804);
lambda_loop1_exit2804: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22804: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2804); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22804); 
lambda_loop2_exit2804: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2804));
JUMP(exit2804); 
lambda2804:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
MOV(R0,IMM(18)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(263)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy1673:
CMP(R3,R5); 
JUMP_EQ(jmpa1673); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1673); 
jmpa1673: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2804: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy1674:
CMP(R3,R5); 
JUMP_EQ(jmpa1674); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1674); 
jmpa1674: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2802: //OUT OF LAMBDA 

 MOV(IND(266), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE not*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12805: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2805); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12805);
lambda_loop1_exit2805: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22805: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2805); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22805); 
lambda_loop2_exit2805: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2805));
JUMP(exit2805); 
lambda2805:
PUSH(FP);
MOV(FP,SP);
MOV(R0,FPARG(2));

CMP(R0,FALSE);

JUMP_EQ(else1477);
MOV(R0,IMM(95)); 

JUMP(if_exit1477);
else1477:
MOV(R0,IMM(93)); 
if_exit1477:
POP(FP);
RETURN;
exit2805: //OUT OF LAMBDA 

 MOV(IND(267), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map_simple*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12806: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2806); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12806);
lambda_loop1_exit2806: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22806: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2806); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22806); 
lambda_loop2_exit2806: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2806));
JUMP(exit2806); 
lambda2806:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(18)); 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(264)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12807: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit2807); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12807);
lambda_loop1_exit2807: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22807: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2807); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22807); 
lambda_loop2_exit2807: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2807));
JUMP(exit2807); 
lambda2807:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,IMM(18)); 
PUSH(R0); 
// IN LAMBDA AAAAA 
MOV(R1,1+2); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12808: 
CMP(R4,2); 
JUMP_GE(lambda_loop1_exit2808); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12808);
lambda_loop1_exit2808: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22808: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2808); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22808); 
lambda_loop2_exit2808: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2808));
JUMP(exit2808); 
lambda2808:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,1));
MOV(R0,INDD(R0,0));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1675:
CMP(R3,R5); 
JUMP_EQ(jmpa1675); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1675); 
jmpa1675: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2808: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(262)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy1676:
CMP(R3,R5); 
JUMP_EQ(jmpa1676); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1676); 
jmpa1676: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2807: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy1677:
CMP(R3,R5); 
JUMP_EQ(jmpa1677); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1677); 
jmpa1677: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2806: //OUT OF LAMBDA 

 MOV(IND(268), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12809: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2809); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12809);
lambda_loop1_exit2809: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22809: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2809); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22809); 
lambda_loop2_exit2809: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2809));
JUMP(exit2809); 
lambda2809:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop233:
 CMP(R1,1);
 JUMP_EQ(finish_lambda_opt233); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop233);
finish_lambda_opt233: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case233); 
MOV(FPARG(2+1),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+1);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case233); 
stack_fix233: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end233); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix233); 
empty_opt_case233:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt233:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt233); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt233);
end_of_nil_case_opt233: 
MOV(STACK(R6),R2); 
stack_fix_end233: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(241)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else1478);
MOV(R0,IMM(18)); 

JUMP(if_exit1478);
else1478:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(183)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(268)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(268)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(195)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12810: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit2810); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12810);
lambda_loop1_exit2810: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22810: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2810); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22810); 
lambda_loop2_exit2810: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2810));
JUMP(exit2810); 
lambda2810:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IND(269)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(195)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1678:
CMP(R3,R5); 
JUMP_EQ(jmpa1678); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1678); 
jmpa1678: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2810: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1679:
CMP(R3,R5); 
JUMP_EQ(jmpa1679); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1679); 
jmpa1679: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit1478:
POP(FP);
RETURN;
exit2809: //OUT OF LAMBDA 

 MOV(IND(269), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(25)); 
PUSH(R0); 
MOV(R0,IMM(118)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(254)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(40)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(183)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(40)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(254)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE l*/
MOV(R0,IMM(40)); 

 MOV(IND(270), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(50)); 
PUSH(R0); 
MOV(R0,IND(270)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(254)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
MOV(R0,IND(270)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IND(270)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IND(270)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(183)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
MOV(R0,IMM(53)); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(93)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(252)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(95)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(252)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(136)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(252)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(105)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(252)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(100)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(244)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
//IN APPLIC 
MOV(R0,IND(248)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(248)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(105)); 
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(118)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(239)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(185)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(184)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(136)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(250)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(174)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(251)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(18)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(241)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(146)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(245)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(129)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(244)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(131)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(246)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(136)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(246)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(153)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(245)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(136)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(245)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(138)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(238)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(32)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(143)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(242)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(18)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(242)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(162)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(240)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(178)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(240)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(267)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(162)); 
PUSH(R0); 
MOV(R0,IMM(146)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(236)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(257)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(164)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(151)); 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12811: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2811); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12811);
lambda_loop1_exit2811: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22811: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2811); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22811); 
lambda_loop2_exit2811: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2811));
JUMP(exit2811); 
lambda2811:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(174)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(233)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(237)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1680:
CMP(R3,R5); 
JUMP_EQ(jmpa1680); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1680); 
jmpa1680: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2811: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(151)); 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12812: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2812); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12812);
lambda_loop1_exit2812: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22812: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2812); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22812); 
lambda_loop2_exit2812: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2812));
JUMP(exit2812); 
lambda2812:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(174)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(234)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(238)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1681:
CMP(R3,R5); 
JUMP_EQ(jmpa1681); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1681); 
jmpa1681: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2812: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(153)); 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12813: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2813); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12813);
lambda_loop1_exit2813: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22813: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2813); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22813); 
lambda_loop2_exit2813: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2813));
JUMP(exit2813); 
lambda2813:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(235)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(110)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(239)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1682:
CMP(R3,R5); 
JUMP_EQ(jmpa1682); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1682); 
jmpa1682: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2813: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(160)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(257)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(158)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(174)); 
PUSH(R0); 
MOV(R0,IMM(30)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(233)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop12814: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit2814); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop12814);
lambda_loop1_exit2814: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop22814: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit2814); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop22814); 
lambda_loop2_exit2814: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda2814));
JUMP(exit2814); 
lambda2814:
PUSH(FP);
MOV(FP,SP);

//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(164)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(258)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(162)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(256)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(166)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(258)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(256)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(260)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(172)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(239)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy1683:
CMP(R3,R5); 
JUMP_EQ(jmpa1683); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy1683); 
jmpa1683: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit2814: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(43)); 
PUSH(R0); 
MOV(R0,IMM(176)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(217)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(32)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(32)); 
PUSH(R0); 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(228)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(180)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
PUSH(IMM(0)); 
MOV(R0,IND(228)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(178)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(228)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(178)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(32)); 
PUSH(R0); 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(226)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(180)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
PUSH(IMM(0)); 
MOV(R0,IND(226)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(240)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(178)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(226)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(178)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,IMM(32)); 
PUSH(R0); 
MOV(R0,IMM(180)); 
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(227)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(232)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(45)); 
PUSH(R0); 
MOV(R0,IMM(43)); 
PUSH(R0); 
MOV(R0,IMM(32)); 
PUSH(R0); 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
PUSH(IMM(5)); 
MOV(R0,IND(230)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,IMM(32)); 
PUSH(R0); 
MOV(R0,IMM(43)); 
PUSH(R0); 
MOV(R0,IMM(45)); 
PUSH(R0); 
PUSH(IMM(5)); 
MOV(R0,IND(231)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 
/*epilogue */ 


STOP_MACHINE;
return 0;
UNDEFINED_VARIABLE_ERROR:
printf("undefined variable \n");
L_ERROR_NOT_CLOSURE:
  printf("aaa\n");
  exit(12);
}
