#define SYMBOL_TABLE 1
#define VOID 2
#define NIL 12
#define FALSE 3
#define TRUE  5

/* THIS IS THE START OF THE PROGRAN */
#include <stdio.h>
#include <stdlib.h>

/* change to 0 for no debug info to be printed: */
#define DO_SHOW 1

#define db {printf("LINE: %d\n",__LINE__);}
#include "arch/cisc.h"
#include "debug.h"
int main()
{
  START_MACHINE;

  JUMP(CONTINUE);

#include "arch/char.lib"
#include "arch/io.lib"
#include "arch/math.lib"
#include "arch/string.lib"
#include "arch/system.lib"
#include "arch/scheme.lib"
  CONTINUE:
  PUSH(IMM(0));
  PUSH(IMM(0));
  PUSH(IMM(0));
  PUSH(IMM(0));
  MOV(FP,SP);


PUSH(IMM(491+1)); 
CALL(MALLOC); 
MOV(R0,IMM(2)); 
DROP(1); 
 
MOV(IND(R0),IMM(937610));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(0));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(42));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(7));
 INCR(R0);
MOV(IND(R0),IMM(722689));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(7));
 INCR(R0);
MOV(IND(R0),IMM(110));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(110));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(110));
 INCR(R0);
MOV(IND(R0),IMM(110));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(-1));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(2));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(4));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(5));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(6));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(7));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(8));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(9));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(10));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(11));
 INCR(R0);

 /*starting global env------------*/ 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 

/* STARTING TO ADD PRIMITIVES */ 
 INCR(R0); 
MOV(IND(47),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cdr));
INCR(R0); 
MOV(IND(48),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_car));
INCR(R0); 
MOV(IND(49),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cons));
INCR(R0); 
MOV(IND(50),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_zero));
INCR(R0); 
MOV(IND(51),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_null));
INCR(R0); 
MOV(IND(52),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_list));
INCR(R0); 
MOV(IND(53),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_pair));
INCR(R0); 
MOV(IND(54),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_plus));
INCR(R0); 
MOV(IND(55),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_minus));
INCR(R0); 
MOV(IND(56),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_mult));
INCR(R0); 
MOV(IND(57),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_div));
INCR(R0); 
MOV(IND(58),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector));
INCR(R0); 
MOV(IND(59),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_apply));
INCR(R0); 
MOV(IND(60),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_string));
INCR(R0); 
MOV(IND(61),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_eq));
INCR(R0); 
MOV(IND(62),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_int));
INCR(R0); 
MOV(IND(63),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_lt));
INCR(R0); 
MOV(IND(64),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_gt));
INCR(R0); 
MOV(IND(65),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_eq));
INCR(R0); 
MOV(IND(66),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_to_symbol));
INCR(R0); 
MOV(IND(67),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_symbol_to_string));
INCR(R0); 
MOV(IND(68),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_vector));
INCR(R0); 
MOV(IND(69),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_bool));
INCR(R0); 
MOV(IND(70),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_string));
INCR(R0); 
MOV(IND(71),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_symbol));
INCR(R0); 
MOV(IND(72),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_vector));
INCR(R0); 
MOV(IND(73),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_proc));
INCR(R0); 
MOV(IND(74),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vec_len));
INCR(R0); 
MOV(IND(75),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_len));
INCR(R0); 
MOV(IND(76),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_denominator));
INCR(R0); 
MOV(IND(77),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_ref));
INCR(R0); 
MOV(IND(78),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_ref));
INCR(R0); 
MOV(IND(79),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_char_to_integer));
INCR(R0); 
MOV(IND(80),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_integer_to_char));
INCR(R0); 
MOV(IND(81),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_remainder));
INCR(R0); 
MOV(IND(82),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_number));
INCR(R0); 
MOV(IND(83),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_numerator));
INCR(R0); 
MOV(IND(84),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_rational));
INCR(R0); 
MOV(IND(85),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_car));
INCR(R0); 
MOV(IND(86),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_cdr));
INCR(R0); 
MOV(IND(87),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_set));
INCR(R0); 
MOV(IND(88),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_set));
INCR(R0); 
MOV(IND(89),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_char));
INCR(R0); 

 //STRING LIST
MOV(IND(1),R0); 
MOV(INDD(R0,0), IMM(7)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R0,0), IMM(T_UNDEFINED)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 


 /*new expr */ 
 
/* IN DEFINE +*/
MOV(R0,IND(54)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(90), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE -*/
MOV(R0,IND(55)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(91), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE **/
MOV(R0,IND(56)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(92), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE /*/
MOV(R0,IND(57)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(93), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE <*/
MOV(R0,IND(63)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(94), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE >*/
MOV(R0,IND(64)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(95), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE =*/
MOV(R0,IND(65)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(96), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-string*/
MOV(R0,IND(60)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(97), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-vector*/
MOV(R0,IND(68)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(98), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-ref*/
MOV(R0,IND(77)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(99), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-ref*/
MOV(R0,IND(78)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(100), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-length*/
MOV(R0,IND(75)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(101), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-length*/
MOV(R0,IND(74)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(102), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE eq?*/
MOV(R0,IND(61)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(103), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE zero?*/
MOV(R0,IND(50)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(104), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE null?*/
MOV(R0,IND(51)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(105), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE pair?*/
MOV(R0,IND(53)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(106), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list?*/
MOV(R0,IND(52)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(107), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol?*/
MOV(R0,IND(71)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(108), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string?*/
MOV(R0,IND(70)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(109), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector?*/
MOV(R0,IND(72)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(110), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE rational?*/
MOV(R0,IND(84)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(111), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE procedure?*/
MOV(R0,IND(73)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(112), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE number?*/
MOV(R0,IND(82)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(113), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer?*/
MOV(R0,IND(62)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(114), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char?*/
MOV(R0,IND(89)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(115), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE boolean?*/
MOV(R0,IND(69)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(116), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-cdr!*/
MOV(R0,IND(86)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(117), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-car!*/
MOV(R0,IND(85)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(118), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-set!*/
MOV(R0,IND(88)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(119), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-set!*/
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(120), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char->integer*/
MOV(R0,IND(79)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(121), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer->char*/
MOV(R0,IND(80)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(122), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol->string*/
MOV(R0,IND(67)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(123), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string->symbol*/
MOV(R0,IND(66)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(124), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop120: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit20); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop120);
lambda_loop1_exit20: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop220: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit20); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop220); 
lambda_loop2_exit20: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda20));
JUMP(exit20); 
lambda20:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop3:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt3); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop3);
finish_lambda_opt3: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case3); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case3); 
stack_fix3: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end3); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix3); 
empty_opt_case3:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt3:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt3); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt3);
end_of_nil_case_opt3: 
MOV(STACK(R6),R2); 
stack_fix_end3: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
MOV(R0,FPARG(2));
POP(FP);
RETURN;
exit20: //OUT OF LAMBDA 

 MOV(IND(125), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldl*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop121: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit21); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop121);
lambda_loop1_exit21: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop221: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit21); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop221); 
lambda_loop2_exit21: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda21));
JUMP(exit21); 
lambda21:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(105)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else8);
MOV(R0,FPARG(3));

JUMP(if_exit8);
else8:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(126)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy15:
CMP(R3,R5); 
JUMP_EQ(jmpa15); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy15); 
jmpa15: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit8:
POP(FP);
RETURN;
exit21: //OUT OF LAMBDA 

 MOV(IND(126), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldr*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop122: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit22); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop122);
lambda_loop1_exit22: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop222: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit22); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop222); 
lambda_loop2_exit22: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda22));
JUMP(exit22); 
lambda22:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(105)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else9);
MOV(R0,FPARG(3));

JUMP(if_exit9);
else9:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(127)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy16:
CMP(R3,R5); 
JUMP_EQ(jmpa16); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy16); 
jmpa16: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit9:
POP(FP);
RETURN;
exit22: //OUT OF LAMBDA 

 MOV(IND(127), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE reverse*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop123: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit23); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop123);
lambda_loop1_exit23: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop223: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit23); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop223); 
lambda_loop2_exit23: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda23));
JUMP(exit23); 
lambda23:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(105)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else11);
MOV(R0,FPARG(3));

JUMP(if_exit11);
else11:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(107)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(131)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else10);
MOV(R0,FPARG(2));

JUMP(if_exit10);
else10:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(128)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy17:
CMP(R3,R5); 
JUMP_EQ(jmpa17); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy17); 
jmpa17: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit10:
if_exit11:
POP(FP);
RETURN;
exit23: //OUT OF LAMBDA 

 MOV(IND(128), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE bin_append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop124: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit24); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop124);
lambda_loop1_exit24: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop224: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit24); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop224); 
lambda_loop2_exit24: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda24));
JUMP(exit24); 
lambda24:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(105)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else13);
MOV(R0,FPARG(3));

JUMP(if_exit13);
else13:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(107)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(131)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else12);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy19:
CMP(R3,R5); 
JUMP_EQ(jmpa19); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy19); 
jmpa19: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit12);
else12:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(129)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy18:
CMP(R3,R5); 
JUMP_EQ(jmpa18); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy18); 
jmpa18: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit12:
if_exit13:
POP(FP);
RETURN;
exit24: //OUT OF LAMBDA 

 MOV(IND(129), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop125: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit25); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop125);
lambda_loop1_exit25: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop225: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit25); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop225); 
lambda_loop2_exit25: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda25));
JUMP(exit25); 
lambda25:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop4:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt4); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop4);
finish_lambda_opt4: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case4); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case4); 
stack_fix4: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end4); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix4); 
empty_opt_case4:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt4:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt4); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt4);
end_of_nil_case_opt4: 
MOV(STACK(R6),R2); 
stack_fix_end4: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop126: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit26); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop126);
lambda_loop1_exit26: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop226: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit26); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop226); 
lambda_loop2_exit26: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda26));
JUMP(exit26); 
lambda26:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(12)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(128)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(129)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy20:
CMP(R3,R5); 
JUMP_EQ(jmpa20); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy20); 
jmpa20: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit26: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop127: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit27); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop127);
lambda_loop1_exit27: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop227: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit27); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop227); 
lambda_loop2_exit27: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda27));
JUMP(exit27); 
lambda27:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
MOV(R0,IMM(12)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(127)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy21:
CMP(R3,R5); 
JUMP_EQ(jmpa21); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy21); 
jmpa21: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit27: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy22:
CMP(R3,R5); 
JUMP_EQ(jmpa22); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy22); 
jmpa22: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit25: //OUT OF LAMBDA 

 MOV(IND(130), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE not*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop128: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit28); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop128);
lambda_loop1_exit28: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop228: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit28); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop228); 
lambda_loop2_exit28: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda28));
JUMP(exit28); 
lambda28:
PUSH(FP);
MOV(FP,SP);
MOV(R0,FPARG(2));

CMP(R0,FALSE);

JUMP_EQ(else14);
MOV(R0,IMM(3)); 

JUMP(if_exit14);
else14:
MOV(R0,IMM(5)); 
if_exit14:
POP(FP);
RETURN;
exit28: //OUT OF LAMBDA 

 MOV(IND(131), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map_simple*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop129: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit29); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop129);
lambda_loop1_exit29: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop229: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit29); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop229); 
lambda_loop2_exit29: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda29));
JUMP(exit29); 
lambda29:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(12)); 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(128)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop130: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit30); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop130);
lambda_loop1_exit30: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop230: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit30); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop230); 
lambda_loop2_exit30: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda30));
JUMP(exit30); 
lambda30:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,IMM(12)); 
PUSH(R0); 
// IN LAMBDA AAAAA 
MOV(R1,1+2); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop131: 
CMP(R4,2); 
JUMP_GE(lambda_loop1_exit31); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop131);
lambda_loop1_exit31: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop231: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit31); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop231); 
lambda_loop2_exit31: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda31));
JUMP(exit31); 
lambda31:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,1));
MOV(R0,INDD(R0,0));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy23:
CMP(R3,R5); 
JUMP_EQ(jmpa23); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy23); 
jmpa23: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit31: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(126)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy24:
CMP(R3,R5); 
JUMP_EQ(jmpa24); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy24); 
jmpa24: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit30: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy25:
CMP(R3,R5); 
JUMP_EQ(jmpa25); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy25); 
jmpa25: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit29: //OUT OF LAMBDA 

 MOV(IND(132), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop132: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit32); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop132);
lambda_loop1_exit32: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop232: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit32); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop232); 
lambda_loop2_exit32: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda32));
JUMP(exit32); 
lambda32:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop5:
 CMP(R1,1);
 JUMP_EQ(finish_lambda_opt5); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop5);
finish_lambda_opt5: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case5); 
MOV(FPARG(2+1),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+1);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case5); 
stack_fix5: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end5); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix5); 
empty_opt_case5:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt5:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt5); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt5);
end_of_nil_case_opt5: 
MOV(STACK(R6),R2); 
stack_fix_end5: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(105)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else15);
MOV(R0,IMM(12)); 

JUMP(if_exit15);
else15:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(132)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(132)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(59)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop133: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit33); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop133);
lambda_loop1_exit33: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop233: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit33); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop233); 
lambda_loop2_exit33: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda33));
JUMP(exit33); 
lambda33:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IND(133)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(59)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy26:
CMP(R3,R5); 
JUMP_EQ(jmpa26); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy26); 
jmpa26: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit33: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy27:
CMP(R3,R5); 
JUMP_EQ(jmpa27); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy27); 
jmpa27: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit15:
POP(FP);
RETURN;
exit32: //OUT OF LAMBDA 

 MOV(IND(133), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE factorial*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop134: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit34); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop134);
lambda_loop1_exit34: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop234: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit34); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop234); 
lambda_loop2_exit34: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda34));
JUMP(exit34); 
lambda34:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(104)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else16);
MOV(R0,IMM(24)); 

JUMP(if_exit16);
else16:
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(12)); 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(24)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(91)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(134)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(10)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy28:
CMP(R3,R5); 
JUMP_EQ(jmpa28); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy28); 
jmpa28: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit16:
POP(FP);
RETURN;
exit34: //OUT OF LAMBDA 

 MOV(IND(134), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE fa*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop135: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit35); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop135);
lambda_loop1_exit35: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop235: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit35); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop235); 
lambda_loop2_exit35: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda35));
JUMP(exit35); 
lambda35:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(104)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else17);
MOV(R0,IMM(13)); 

JUMP(if_exit17);
else17:
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(22)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(90)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(135)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy29:
CMP(R3,R5); 
JUMP_EQ(jmpa29); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy29); 
jmpa29: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit17:
POP(FP);
RETURN;
exit35: //OUT OF LAMBDA 

 MOV(IND(135), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(30)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(134)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(44)); 
PUSH(R0); 
MOV(R0,IMM(42)); 
PUSH(R0); 
MOV(R0,IMM(40)); 
PUSH(R0); 
MOV(R0,IMM(38)); 
PUSH(R0); 
MOV(R0,IMM(36)); 
PUSH(R0); 
MOV(R0,IMM(34)); 
PUSH(R0); 
MOV(R0,IMM(32)); 
PUSH(R0); 
MOV(R0,IMM(30)); 
PUSH(R0); 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,IMM(26)); 
PUSH(R0); 
MOV(R0,IMM(24)); 
PUSH(R0); 
PUSH(IMM(11)); 
MOV(R0,IND(93)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 
/*epilogue */ 


STOP_MACHINE;
return 0;
UNDEFINED_VARIABLE_ERROR:
printf("undefined variable \n");
L_ERROR_NOT_CLOSURE:
  printf("aaa\n");
  exit(12);
}
