#define SYMBOL_TABLE 1
#define VOID 2
#define NIL 5
#define FALSE 3
#define TRUE  6

/* THIS IS THE START OF THE PROGRAN */
#include <stdio.h>
#include <stdlib.h>

/* change to 0 for no debug info to be printed: */
#define DO_SHOW 1

#define db {printf("LINE: %d\n",__LINE__);}
#include "arch/cisc.h"
#include "debug.h"
int main()
{
  START_MACHINE;

  JUMP(CONTINUE);

#include "arch/char.lib"
#include "arch/io.lib"
#include "arch/math.lib"
#include "arch/string.lib"
#include "arch/system.lib"
#include "arch/scheme.lib"
  CONTINUE:
  PUSH(IMM(0)); 
  PUSH(IMM(0));
  PUSH(IMM(0));
  PUSH(IMM(0));
  MOV(FP,SP);


PUSH(IMM(475+1)); 
CALL(MALLOC); 
MOV(R0,IMM(2)); 
DROP(1); 
 
MOV(IND(R0),IMM(937610));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(0));
 INCR(R0);
MOV(IND(R0),IMM(722689));
 INCR(R0);
MOV(IND(R0),IMM(741553));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(5));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(1));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(98));
 INCR(R0);
MOV(IND(R0),IMM(99));
 INCR(R0);
MOV(IND(R0),IMM(368031));
 INCR(R0);
MOV(IND(R0),IMM(12));
 INCR(R0);
MOV(IND(R0),IMM(799345));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(3));
 INCR(R0);
MOV(IND(R0),IMM(181048));
 INCR(R0);
MOV(IND(R0),IMM(97));
 INCR(R0);
MOV(IND(R0),IMM(945311));
 INCR(R0);
MOV(IND(R0),IMM(0));
 INCR(R0);

 /*starting global env------------*/ 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 
MOV(IND(R0),IMM(T_UNDEFINED)); INCR(R0); 

/* STARTING TO ADD PRIMITIVES */ 
 INCR(R0); 
MOV(IND(31),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cdr));
INCR(R0); 
MOV(IND(32),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_car));
INCR(R0); 
MOV(IND(33),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_cons));
INCR(R0); 
MOV(IND(34),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_zero));
INCR(R0); 
MOV(IND(35),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_null));
INCR(R0); 
MOV(IND(36),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_list));
INCR(R0); 
MOV(IND(37),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_pair));
INCR(R0); 
MOV(IND(38),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_plus));
INCR(R0); 
MOV(IND(39),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_minus));
INCR(R0); 
MOV(IND(40),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_mult));
INCR(R0); 
MOV(IND(41),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_div));
INCR(R0); 
MOV(IND(42),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector));
INCR(R0); 
MOV(IND(43),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_apply));
INCR(R0); 
MOV(IND(44),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_string));
INCR(R0); 
MOV(IND(45),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_eq));
INCR(R0); 
MOV(IND(46),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_int));
INCR(R0); 
MOV(IND(47),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_lt));
INCR(R0); 
MOV(IND(48),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_gt));
INCR(R0); 
MOV(IND(49),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_v_eq));
INCR(R0); 
MOV(IND(50),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_to_symbol));
INCR(R0); 
MOV(IND(51),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_symbol_to_string));
INCR(R0); 
MOV(IND(52),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_make_vector));
INCR(R0); 
MOV(IND(53),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_bool));
INCR(R0); 
MOV(IND(54),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_string));
INCR(R0); 
MOV(IND(55),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_symbol));
INCR(R0); 
MOV(IND(56),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_vector));
INCR(R0); 
MOV(IND(57),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_proc));
INCR(R0); 
MOV(IND(58),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vec_len));
INCR(R0); 
MOV(IND(59),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_len));
INCR(R0); 
MOV(IND(60),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_denominator));
INCR(R0); 
MOV(IND(61),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_ref));
INCR(R0); 
MOV(IND(62),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_ref));
INCR(R0); 
MOV(IND(63),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_char_to_integer));
INCR(R0); 
MOV(IND(64),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_integer_to_char));
INCR(R0); 
MOV(IND(65),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_remainder));
INCR(R0); 
MOV(IND(66),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_number));
INCR(R0); 
MOV(IND(67),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_numerator));
INCR(R0); 
MOV(IND(68),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_rational));
INCR(R0); 
MOV(IND(69),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_car));
INCR(R0); 
MOV(IND(70),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_set_cdr));
INCR(R0); 
MOV(IND(71),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_string_set));
INCR(R0); 
MOV(IND(72),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_vector_set));
INCR(R0); 
MOV(IND(73),R0);
MOV(IND(R0), IMM(T_CLOSURE)); 
INCR(R0);
MOV(IND(R0),IMM(2131));
INCR(R0); 
MOV(IND(R0), LABEL(L_is_char));
INCR(R0); 

 //STRING LIST
MOV(IND(1),R0); 
MOV(INDD(R0,0), IMM(12)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 
MOV(INDD(R0,0), IMM(T_UNDEFINED)); 
MOV(R1,R0); 
ADD(R0,IMM(2)); 


 /*new expr */ 
 
/* IN DEFINE +*/
MOV(R0,IND(38)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(74), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE -*/
MOV(R0,IND(39)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(75), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE **/
MOV(R0,IND(40)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(76), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE /*/
MOV(R0,IND(41)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(77), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE <*/
MOV(R0,IND(47)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(78), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE >*/
MOV(R0,IND(48)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(79), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE =*/
MOV(R0,IND(49)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(80), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-string*/
MOV(R0,IND(44)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(81), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE make-vector*/
MOV(R0,IND(52)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(82), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-ref*/
MOV(R0,IND(61)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(83), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-ref*/
MOV(R0,IND(62)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(84), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-length*/
MOV(R0,IND(59)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(85), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-length*/
MOV(R0,IND(58)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(86), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE eq?*/
MOV(R0,IND(45)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(87), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE zero?*/
MOV(R0,IND(34)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(88), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE null?*/
MOV(R0,IND(35)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(89), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE pair?*/
MOV(R0,IND(37)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(90), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list?*/
MOV(R0,IND(36)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(91), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol?*/
MOV(R0,IND(55)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(92), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string?*/
MOV(R0,IND(54)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(93), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector?*/
MOV(R0,IND(56)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(94), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE rational?*/
MOV(R0,IND(68)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(95), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE procedure?*/
MOV(R0,IND(57)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(96), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE number?*/
MOV(R0,IND(66)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(97), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer?*/
MOV(R0,IND(46)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(98), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char?*/
MOV(R0,IND(73)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(99), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE boolean?*/
MOV(R0,IND(53)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(100), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-cdr!*/
MOV(R0,IND(70)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(101), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE set-car!*/
MOV(R0,IND(69)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(102), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE vector-set!*/
MOV(R0,IND(72)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(103), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string-set!*/
MOV(R0,IND(71)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(104), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE char->integer*/
MOV(R0,IND(63)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(105), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE integer->char*/
MOV(R0,IND(64)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(106), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE symbol->string*/
MOV(R0,IND(51)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(107), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE string->symbol*/
MOV(R0,IND(50)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);

 MOV(IND(108), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE list*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1112: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit112); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1112);
lambda_loop1_exit112: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2112: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit112); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2112); 
lambda_loop2_exit112: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda112));
JUMP(exit112); 
lambda112:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop24:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt24); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop24);
finish_lambda_opt24: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case24); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case24); 
stack_fix24: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end24); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix24); 
empty_opt_case24:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt24:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt24); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt24);
end_of_nil_case_opt24: 
MOV(STACK(R6),R2); 
stack_fix_end24: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
MOV(R0,FPARG(2));
POP(FP);
RETURN;
exit112: //OUT OF LAMBDA 

 MOV(IND(109), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldl*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1113: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit113); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1113);
lambda_loop1_exit113: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2113: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit113); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2113); 
lambda_loop2_exit113: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda113));
JUMP(exit113); 
lambda113:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(89)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else64);
MOV(R0,FPARG(3));

JUMP(if_exit64);
else64:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(31)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(32)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(110)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy104:
CMP(R3,R5); 
JUMP_EQ(jmpa104); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy104); 
jmpa104: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit64:
POP(FP);
RETURN;
exit113: //OUT OF LAMBDA 

 MOV(IND(110), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE foldr*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1114: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit114); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1114);
lambda_loop1_exit114: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2114: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit114); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2114); 
lambda_loop2_exit114: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda114));
JUMP(exit114); 
lambda114:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(89)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else65);
MOV(R0,FPARG(3));

JUMP(if_exit65);
else65:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(31)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(4));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(32)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,FPARG(2));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(111)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy105:
CMP(R3,R5); 
JUMP_EQ(jmpa105); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy105); 
jmpa105: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit65:
POP(FP);
RETURN;
exit114: //OUT OF LAMBDA 

 MOV(IND(111), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE reverse*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1115: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit115); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1115);
lambda_loop1_exit115: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2115: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit115); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2115); 
lambda_loop2_exit115: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda115));
JUMP(exit115); 
lambda115:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(89)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else67);
MOV(R0,FPARG(3));

JUMP(if_exit67);
else67:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(91)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(115)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else66);
MOV(R0,FPARG(2));

JUMP(if_exit66);
else66:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(32)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(33)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(31)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(112)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy106:
CMP(R3,R5); 
JUMP_EQ(jmpa106); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy106); 
jmpa106: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit66:
if_exit67:
POP(FP);
RETURN;
exit115: //OUT OF LAMBDA 

 MOV(IND(112), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE bin_append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1116: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit116); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1116);
lambda_loop1_exit116: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2116: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit116); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2116); 
lambda_loop2_exit116: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda116));
JUMP(exit116); 
lambda116:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(89)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else69);
MOV(R0,FPARG(3));

JUMP(if_exit69);
else69:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(91)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(115)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else68);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(33)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy108:
CMP(R3,R5); 
JUMP_EQ(jmpa108); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy108); 
jmpa108: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 

JUMP(if_exit68);
else68:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(32)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(33)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(31)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(113)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy107:
CMP(R3,R5); 
JUMP_EQ(jmpa107); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy107); 
jmpa107: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit68:
if_exit69:
POP(FP);
RETURN;
exit116: //OUT OF LAMBDA 

 MOV(IND(113), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE append*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1117: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit117); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1117);
lambda_loop1_exit117: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2117: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit117); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2117); 
lambda_loop2_exit117: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda117));
JUMP(exit117); 
lambda117:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop25:
 CMP(R1,0);
 JUMP_EQ(finish_lambda_opt25); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop25);
finish_lambda_opt25: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case25); 
MOV(FPARG(2+0),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+0);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case25); 
stack_fix25: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end25); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix25); 
empty_opt_case25:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt25:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt25); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt25);
end_of_nil_case_opt25: 
MOV(STACK(R6),R2); 
stack_fix_end25: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1118: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit118); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1118);
lambda_loop1_exit118: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2118: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit118); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2118); 
lambda_loop2_exit118: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda118));
JUMP(exit118); 
lambda118:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(5)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(112)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(113)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy109:
CMP(R3,R5); 
JUMP_EQ(jmpa109); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy109); 
jmpa109: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit118: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1119: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit119); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1119);
lambda_loop1_exit119: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2119: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit119); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2119); 
lambda_loop2_exit119: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda119));
JUMP(exit119); 
lambda119:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
MOV(R0,IMM(5)); 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(111)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy110:
CMP(R3,R5); 
JUMP_EQ(jmpa110); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy110); 
jmpa110: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit119: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy111:
CMP(R3,R5); 
JUMP_EQ(jmpa111); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy111); 
jmpa111: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit117: //OUT OF LAMBDA 

 MOV(IND(114), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE not*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1120: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit120); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1120);
lambda_loop1_exit120: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2120: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit120); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2120); 
lambda_loop2_exit120: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda120));
JUMP(exit120); 
lambda120:
PUSH(FP);
MOV(FP,SP);
MOV(R0,FPARG(2));

CMP(R0,FALSE);

JUMP_EQ(else70);
MOV(R0,IMM(3)); 

JUMP(if_exit70);
else70:
MOV(R0,IMM(6)); 
if_exit70:
POP(FP);
RETURN;
exit120: //OUT OF LAMBDA 

 MOV(IND(115), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map_simple*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1121: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit121); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1121);
lambda_loop1_exit121: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2121: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit121); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2121); 
lambda_loop2_exit121: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda121));
JUMP(exit121); 
lambda121:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(5)); 
PUSH(R0); 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(112)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1122: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit122); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1122);
lambda_loop1_exit122: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2122: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit122); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2122); 
lambda_loop2_exit122: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda122));
JUMP(exit122); 
lambda122:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
MOV(R0,IMM(5)); 
PUSH(R0); 
// IN LAMBDA AAAAA 
MOV(R1,1+2); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1123: 
CMP(R4,2); 
JUMP_GE(lambda_loop1_exit123); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1123);
lambda_loop1_exit123: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2123: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit123); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2123); 
lambda_loop2_exit123: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda123));
JUMP(exit123); 
lambda123:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
//IN APPLIC 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,1));
MOV(R0,INDD(R0,0));
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(33)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy112:
CMP(R3,R5); 
JUMP_EQ(jmpa112); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy112); 
jmpa112: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit123: //OUT OF LAMBDA 
PUSH(R0); 
PUSH(IMM(3)); 
MOV(R0,IND(110)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+3+3); 
tail_call_copy113:
CMP(R3,R5); 
JUMP_EQ(jmpa113); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy113); 
jmpa113: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit122: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+1+3); 
tail_call_copy114:
CMP(R3,R5); 
JUMP_EQ(jmpa114); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy114); 
jmpa114: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit121: //OUT OF LAMBDA 

 MOV(IND(116), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE map*/
// IN LAMBDA AAAAA 
MOV(R1,1+0); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1124: 
CMP(R4,0); 
JUMP_GE(lambda_loop1_exit124); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1124);
lambda_loop1_exit124: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2124: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit124); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2124); 
lambda_loop2_exit124: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda124));
JUMP(exit124); 
lambda124:
PUSH(FP);
MOV(FP,SP);
MOV(R1,FPARG(1)); 
MOV(R2,NIL); 
lambda_opt_loop26:
 CMP(R1,1);
 JUMP_EQ(finish_lambda_opt26); 
 PUSH(R2); 
 PUSH(FPARG(R1+1)); 
 CALL(MAKE_SOB_PAIR);
 DROP(2); 
 SUB(R1,1); 
 MOV(R2,R0); 
 JUMP(lambda_opt_loop26);
finish_lambda_opt26: 
CMP(IND(R2),T_NIL); 
JUMP_EQ(empty_opt_case26); 
MOV(FPARG(2+1),R2); 
MOV(R4,FP); 
 SUB(R4,IMM(4)); 
SUB(R4,FPARG(1)); // now r4 should hold number of old args 
MOV(FPARG(1),1+1);
MOV(R3,FP); // now r3 should hold new number of args 
SUB(R3,IMM(4)); 
SUB(R3,FPARG(1)); 
MOV(R5,R3); 
SUB(R5,R4); 
JUMP_EQ(empty_opt_case26); 
stack_fix26: 
 CMP(R3,SP); 
 JUMP_EQ(stack_fix_end26); 
 MOV(STACK(R4),STACK(R3)); 
 INCR(R4); 
 INCR(R3); 
 JUMP(stack_fix26); 
empty_opt_case26:
  MOV(R5,IMM(-1)); 
 MOV(R6,SP);
  MOV(R3,SP); 
 DECR(R3); 
  MOV(R4,FP); 
  SUB(R4,IMM(4)); 
 SUB(R4,FPARG(1)); // now r4 should hold number of old args 
empty_opt26:
 CMP(R3,R4); 
 JUMP_LT(end_of_nil_case_opt26); 
 MOV(STACK(R6),STACK(R3)); 
 DECR(R6); 
 DECR(R3); 
 JUMP(empty_opt26);
end_of_nil_case_opt26: 
MOV(STACK(R6),R2); 
stack_fix_end26: 
//need to fix the stack pointer stuff now 
SUB(SP,R5); 
MOV(FP,SP); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(32)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(89)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

CMP(R0,FALSE);

JUMP_EQ(else71);
MOV(R0,IMM(5)); 

JUMP(if_exit71);
else71:
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(31)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(116)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,IND(32)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(116)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(43)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
// IN LAMBDA AAAAA 
MOV(R1,1+1); 
PUSH(R1); 
CALL(MALLOC);
MOV(R1,R0); 
DROP(1); 
MOV(R2, FPARG(0)); 
MOV(R4,0); 
MOV(R5,1); 
lambda_loop1125: 
CMP(R4,1); 
JUMP_GE(lambda_loop1_exit125); 
MOV(R3, INDD(R2,R4)); 
MOV(INDD(R1,R5), R3); 
INCR(R4); 
INCR(R5); 
JUMP(lambda_loop1125);
lambda_loop1_exit125: 
PUSH(FPARG(1)); 
CALL(MALLOC); 
DROP(1); 
MOV(R4,0); 
lambda_loop2125: 
CMP(R4,FPARG(1)); 
JUMP_GE(lambda_loop2_exit125); 
MOV(R3,FPARG(2+R4)); 
MOV(INDD(R0,R4),R3); 
INCR(R4); 
JUMP(lambda_loop2125); 
lambda_loop2_exit125: 
MOV(INDD(R1,0),R0); 
PUSH(IMM(3)); 
CALL(MALLOC); 
DROP(1); 
MOV(INDD(R0,0),T_CLOSURE);
MOV(INDD(R0,1),R1); 
MOV(INDD(R0,2),LABEL(lambda125));
JUMP(exit125); 
lambda125:
PUSH(FP);
MOV(FP,SP);
//IN APPLIC 
//IN APPLIC 
//IN APPLIC 
MOV(R0,FPARG(3));
PUSH(R0); 
MOV(R0,FPARG(0));
MOV(R0,INDD(R0,0));
MOV(R0,INDD(R0,0));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(33)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IND(117)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(43)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,FPARG(2));
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(33)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy115:
CMP(R3,R5); 
JUMP_EQ(jmpa115); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy115); 
jmpa115: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
POP(FP);
RETURN;
exit125: //OUT OF LAMBDA 
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
PUSH(FPARG(-1));
MOV(R2,FP); 
SUB(R2,(FPARG(1)+4)); 
MOV(R3,FP); 
MOV(FP,FPARG(-2));
MOV(R5,R3+2+3); 
tail_call_copy116:
CMP(R3,R5); 
JUMP_EQ(jmpa116); 
 MOV(STACK(R2),STACK(R3)); 
 ADD(R3,1); 
 ADD(R2,1); 
 JUMP(tail_call_copy116); 
jmpa116: 
MOV(SP,R2); 
JUMPA(INDD(R0,2)); 
if_exit71:
POP(FP);
RETURN;
exit124: //OUT OF LAMBDA 

 MOV(IND(117), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(8)); 
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(97)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(6)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(10)); 
PUSH(R0); 
MOV(R0,IMM(10)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(10)); 
PUSH(R0); 
MOV(R0,IMM(10)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(74)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(10)); 
PUSH(R0); 
MOV(R0,IMM(10)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(74)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(12)); 
PUSH(R0); 
MOV(R0,IMM(12)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE a*/
MOV(R0,IMM(17)); 

 MOV(IND(118), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IND(118)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(1)); 
MOV(R0,IND(107)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(12)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(26)); 
PUSH(R0); 
MOV(R0,IMM(26)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(26)); 
PUSH(R0); 
MOV(R0,IMM(24)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(81)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
MOV(R0,IMM(19)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
MOV(R0,IMM(19)); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
MOV(R0,IMM(26)); 
PUSH(R0); 
MOV(R0,IMM(24)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(81)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
/* IN DEFINE 3a*/
//IN APPLIC 
MOV(R0,IMM(26)); 
PUSH(R0); 
MOV(R0,IMM(24)); 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(81)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 

 MOV(IND(119), R0);
MOV(R0,VOID); 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 

 /*new expr */ 
 
//IN APPLIC 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,IND(119)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(84)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
//IN APPLIC 
MOV(R0,IMM(28)); 
PUSH(R0); 
MOV(R0,IND(119)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(84)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0); 
PUSH(IMM(2)); 
MOV(R0,IND(87)); 
CMP(R0,T_UNDEFINED); 
JUMP_EQ(UNDEFINED_VARIABLE_ERROR);
PUSH(R0);
CALL(IS_SOB_CLOSURE); 
CMP(R0,0); 
JUMP_EQ(L_ERROR_NOT_CLOSURE);
POP(R0); 
PUSH(INDD(R0,1));
CALLA(INDD(R0,2));
POP(R1); 
POP(R1); 
DROP(R1); 
 //OUT OF APPLIC 
PUSH(R0);
CALL(PRINT_EXPR);
DROP(1); 
/*epilogue */ 


STOP_MACHINE;
return 0;
UNDEFINED_VARIABLE_ERROR:
printf("undefined variable \n");
L_ERROR_NOT_CLOSURE:
  printf("aaa\n");
  exit(12);
}
