/* primitive implementations */
#define FUNC_START \
  PUSH(FP); \
  MOV(FP,SP); 
#define FUNC_END \
  POP(FP); \
  RETURN;
#define PARAM(i) FPARG(i+2) 
#define NUMBER FPARG(1)
#define CHECK_ARGS(HAVE) \
  CMP(NUMBER,HAVE); \
  JUMP_NE(ERROR_NUMBER_OF_ARGS);
#define CHECK_TYPE(type,obj)  \
  CMP(type, IND(obj)); \
  JUMP_NE(ERROR_TYPE_MIS_MATCH);
L_cons:
FUNC_START;
CHECK_ARGS(2);
PUSH(PARAM(0));
PUSH(PARAM(1));
CALL(MAKE_SOB_PAIR);
DROP(2);
FUNC_END

L_car:
FUNC_START
CHECK_ARGS(1);
CHECK_TYPE(T_PAIR, PARAM(0));
MOV(R0,PARAM(0));
MOV(R0, INDD(R0,1));
FUNC_END

L_cdr:
FUNC_START
CHECK_ARGS(1);
CHECK_TYPE(T_PAIR, PARAM(0));
MOV(R0,PARAM(0));
MOV(R0, INDD(R0,2));
FUNC_END



L_bin_plus: 
FUNC_START
CHECK_ARGS(2);
CHECK_TYPE(T_INTEGER, PARAM(0));
CHECK_TYPE(T_INTEGER, PARAM(1));
MOV(R0,PARAM(0));
MOV(R0,INDD(R0,1));
MOV(R1,PARAM(1));
MOV(R1,INDD(R1,1));
ADD(R0,R1);
PUSH(R0);
CALL(MAKE_SOB_INTEGER);
DROP(1);
FUNC_END;



ERROR_NUMBER_OF_ARGS:
ERROR_TYPE_MIS_MATCH:
  exit(12);

 
